from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
import os

def generate_analysis_pdf(analysis_data, output_path):
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#0284c7"),
        spaceAfter=20
    )
    story.append(Paragraph(f"Resume Analysis: {analysis_data['filename']}", title_style))
    story.append(Spacer(1, 12))

    # ATS Score
    score_style = ParagraphStyle(
        'ScoreStyle',
        parent=styles['Normal'],
        fontSize=18,
        textColor=colors.HexColor("#0ea5e9"),
        spaceAfter=20
    )
    story.append(Paragraph(f"ATS Score: {analysis_data['ats_score']}/100", score_style))
    story.append(Spacer(1, 12))

    # Suggestions Header
    story.append(Paragraph("AI Suggestions & Feedback", styles['Heading2']))
    story.append(Spacer(1, 6))

    # Suggestions Content
    suggestion_style = styles['Normal']
    suggestion_style.leading = 14
    
    # Split suggestions by double newlines or single newlines to create paragraphs
    for para in analysis_data['suggestions'].split('\n'):
        if para.strip():
            story.append(Paragraph(para.strip(), suggestion_style))
            story.append(Spacer(1, 8))

    # Footer
    story.append(Spacer(1, 40))
    footer_style = ParagraphStyle(
        'FooterStyle',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.grey,
        alignment=1
    )
    story.append(Paragraph("Generated by ResuAI - Your AI Resume Partner", footer_style))

    doc.build(story)
    return output_path
